import { Contact } from './types';

export const RAW_CONTACTS: Omit<Contact, 'id'>[] = [
  { ramal: "5430", nome: "DHO", departamento: "DHO" },
  { ramal: "5162", nome: "ADALBERTO", departamento: "FISCAL" },
  { ramal: "5241", nome: "ADRIANO", departamento: "COI" },
  { ramal: "5319", nome: "ADRIEL", departamento: "PCP" },
  { ramal: "5245", nome: "AECIO", departamento: "MEIO AMBIENTE" },
  { ramal: "5388", nome: "AGENTES SIF", departamento: "SIF - AGENTES" },
  { ramal: "5316", nome: "ALESSANDRA MONTANARI", departamento: "SECRETÁRIA DIRETORIA" },
  { ramal: "5318", nome: "ALEX", departamento: "LOGISTICA" },
  { ramal: "5250", nome: "ALISON", departamento: "TI - INDUSTRIA" },
  { ramal: "5317", nome: "ALMOXARIFADO", departamento: "ALMOXARIFADO" },
  { ramal: "5423", nome: "ALMOXARIFADO", departamento: "ALMOXARIFADO" },
  { ramal: "5422", nome: "ALMOXARIFADO", departamento: "ALMOXARIFADO" },
  { ramal: "5445", nome: "ALMOXARIFADO MESANINO", departamento: "ALMOXARIFADO" },
  { ramal: "5710", nome: "AMANDA CAMPOS", departamento: "ADMINISTRATIVO" },
  { ramal: "5342", nome: "AMARO", departamento: "TENDAL / QUEBRA" },
  { ramal: "5231", nome: "ANA CAROLINA SANTOS", departamento: "EXPORTAÇÃO" },
  { ramal: "5251", nome: "ANA LIDIA", departamento: "LABORATORIO" },
  { ramal: "5306", nome: "ANDRE BARBOSA", departamento: "LOGISTICA" },
  { ramal: "5239", nome: "ANDRE FLAUZINO", departamento: "TI - GERENCIA" },
  { ramal: "5378", nome: "ANFITEATRO / TREINAMENTO", departamento: "ANFITEATRO" },
  { ramal: "5413", nome: "ANTONIO SANTOS", departamento: "COMPRA DE GADO" },
  { ramal: "5715", nome: "AREA SUJA ABATE", departamento: "INDUSTRIA" },
  { ramal: "5249", nome: "AUTOMAÇÃO", departamento: "PROJETOS" },
  { ramal: "5331", nome: "BALANÇÃO", departamento: "FATURAMENTO" },
  { ramal: "5427", nome: "BEA RECEPCAO", departamento: "BEA" },
  { ramal: "5226", nome: "BRUNO/ YURI MAPA ABATE", departamento: "CORREDOR CÂMARAS" },
  { ramal: "5227", nome: "CAIO TORTORO", departamento: "CONTROLADORIA FINANCEIRA" },
  { ramal: "5206", nome: "CALDEIRA", departamento: "CALDEIRA" },
  { ramal: "5248", nome: "CAROLINA ANDRADE", departamento: "FINANCEIRO" },
  { ramal: "5421", nome: "CESAR", departamento: "CONTROLE DE QUALIDADE" },
  { ramal: "5346", nome: "CLAUDIA", departamento: "LABORATORIO" },
  { ramal: "996416", nome: "CLAUDIO", departamento: "TRANSPORTE" },
  { ramal: "5367", nome: "CLAUDIO", departamento: "SALA DE TRANSPORTE" },
  { ramal: "5216", nome: "CLEITON ARAUJO", departamento: "UTILIDADES" },
  { ramal: "5439", nome: "CONTAINER/INFERMARIA", departamento: "SAÚDE" },
  { ramal: "5407", nome: "CONTROLADORIA DE NEGOCIOS", departamento: "CONTROLADORIA DE NEGOCIOS" },
  { ramal: "5379", nome: "CRISTIANE TROPALDI", departamento: "RASTREABILIDADE" },
  { ramal: "5225", nome: "DANIELLE", departamento: "RH" },
  { ramal: "5307", nome: "DANIELLE FIORI", departamento: "COMERCIAL" },
  { ramal: "5447", nome: "DANILA", departamento: "CONTROLADORIA DE NEGOCIOS" },
  { ramal: "5228", nome: "DANILO SILVA", departamento: "SUPRIMENTOS" },
  { ramal: "5320", nome: "DEBORA", departamento: "DP" },
  { ramal: "5213", nome: "DESOSSA CAIXARIA ETIQUETA", departamento: "DESOSSA" },
  { ramal: "5360", nome: "DESOSSA MONTAGEM DE CAIXAS", departamento: "CAXARIA DESOSSA" },
  { ramal: "5201", nome: "DESOSSA/ ILDO", departamento: "DESOSSA" },
  { ramal: "5409", nome: "DIEGO REZENDE", departamento: "EXPORTAÇAO" },
  { ramal: "5371", nome: "DIEGO SANTOS", departamento: "GERENCIA INDUSTRIAL" },
  { ramal: "5383", nome: "DIRCEU ORANGES", departamento: "DIRETOR" },
  { ramal: "5403", nome: "DISPONIVEL", departamento: "GERAL" },
  { ramal: "5438", nome: "DISPONIVEL", departamento: "GERAL" },
  { ramal: "5380", nome: "DOUTORES: FELIPE E HENRIQUE", departamento: "SIF" },
  { ramal: "5308", nome: "EDUARDO ALVES", departamento: "TI" },
  { ramal: "5347", nome: "EDUARDO ORANGES", departamento: "DIRETOR" },
  { ramal: "5338", nome: "EMBARQUE", departamento: "TENDAL" },
  { ramal: "5229", nome: "EMILLY ROSA", departamento: "EXPORTAÇÃO" },
  { ramal: "5390", nome: "ERICA", departamento: "SIF - DCPOA" },
  { ramal: "5335", nome: "EXPEDICAO VALDICO / MOISES", departamento: "RESFRIADOS" },
  { ramal: "5334", nome: "FABIANE", departamento: "BEA" },
  { ramal: "5375", nome: "FABIOLA", departamento: "LABORATORIO" },
  { ramal: "5220", nome: "FABRICIO", departamento: "COMPRAS" },
  { ramal: "5217", nome: "FELIPE ORANGES", departamento: "DIRETOR" },
  { ramal: "5429", nome: "FERRAMENTARIA", departamento: "MANUTENCAO" },
  { ramal: "5252", nome: "FINANCEIRO", departamento: "FINANCEIRO" },
  { ramal: "5311", nome: "GABRIELA", departamento: "EXPORTAÇÃO" },
  { ramal: "5356", nome: "GABRIELE REIS", departamento: "ENFERMARIA" },
  { ramal: "5444", nome: "GIOVANNI", departamento: "MARKETING" },
  { ramal: "5209", nome: "GIULIANA", departamento: "ERGONOMIA" },
  { ramal: "5339", nome: "GRAXARIA", departamento: "GRAXARIA" },
  { ramal: "5358", nome: "GUILHERME BRANDAO", departamento: "JURIDICO" },
  { ramal: "5711", nome: "GUILHERME CARVALHO", departamento: "LOGISTICA" },
  { ramal: "5322", nome: "GUILHERME ORANGES", departamento: "DIRETOR" },
  { ramal: "5406", nome: "HEIDY", departamento: "CONTROLADORIA DE NEGOCIOS" },
  { ramal: "5709", nome: "HENRIQUE CANDIDO", departamento: "CONTROLADORIA FINANCEIRA" },
  { ramal: "5401", nome: "HIAGO PAVRET OSSES", departamento: "CONTROLE DE QUALIDADE" },
  { ramal: "5704", nome: "IARA / NARJARA", departamento: "DHO" },
  { ramal: "5387", nome: "INSPEÇÃO", departamento: "DIF" },
  { ramal: "5236", nome: "ISADORA GODINHO SILVA", departamento: "DP" },
  { ramal: "5366", nome: "JACQUELINE SANTOS", departamento: "FISCAL" },
  { ramal: "5329", nome: "JAIME", departamento: "GERENTE INDUSTRIAL" },
  { ramal: "5705", nome: "JANAINA", departamento: "JURIDICO" },
  { ramal: "5238", nome: "JANE", departamento: "FINANCEIRO" },
  { ramal: "5235", nome: "JIHAD YOUSSEF", departamento: "HALAL" },
  { ramal: "5299", nome: "JOAO", departamento: "CONTROLE DE QUALIDADE" },
  { ramal: "5242", nome: "JOAO LIMA", departamento: "FISCAL" },
  { ramal: "5303", nome: "JOAO LUCAS FERREIRA", departamento: "COMPRA DE GADO" },
  { ramal: "5345", nome: "JOÃO MARCOS SILVA", departamento: "COMERCIAL" },
  { ramal: "5361", nome: "JOAO NOVETI", departamento: "EXPORTAÇÃO" },
  { ramal: "5353", nome: "JOÃO VICTOR", departamento: "CONTROLE DE QUALIDADE" },
  { ramal: "5207", nome: "JOHNNY", departamento: "AUTOMAÇÃO INDUSTRIAL" },
  { ramal: "5442", nome: "JORGE MARTINS", departamento: "Geral" },
  { ramal: "5230", nome: "JOSE ANTONIO BOCALAO", departamento: "COMERCIAL" },
  { ramal: "5714", nome: "JOSE OLIVEIRA PEIXE", departamento: "TI" },
  { ramal: "5400", nome: "JULIANA", departamento: "DP" },
  { ramal: "5337", nome: "JULIO CESAR", departamento: "MANUTENCAO" },
  { ramal: "5219", nome: "JURIDICO", departamento: "JURIDICO" },
  { ramal: "5426", nome: "KALINE SANTOS", departamento: "CONTROLE DE QUALIDADE" },
  { ramal: "5341", nome: "KEITTY", departamento: "EXPORTAÇÃO" },
  { ramal: "5436", nome: "LARA", departamento: "DP" },
  { ramal: "5364", nome: "LAVADOR", departamento: "LAVADOR" },
  { ramal: "5374", nome: "LAVANDERIA", departamento: "LAVANDERIA" },
  { ramal: "5419", nome: "LAVANDERIA SUJA", departamento: "LAVANDERIA" },
  { ramal: "5418", nome: "LEONARDO", departamento: "EXPORTAÇÃO" },
  { ramal: "5332", nome: "LEONARDO / RODRIGO", departamento: "FATURAMENTO" },
  { ramal: "5343", nome: "LEONARDO SANTOS", departamento: "COMPRAS" },
  { ramal: "5208", nome: "LUCIA", departamento: "DP" },
  { ramal: "5325", nome: "LUCIANO GARCIA", departamento: "COMERCIAL" },
  { ramal: "5321", nome: "LUCIANO SARANSO", departamento: "FINANCEIRO" },
  { ramal: "5414", nome: "LUIZA", departamento: "FINANCEIRO" },
  { ramal: "5417", nome: "MARCELO MOREIRA", departamento: "PCP" },
  { ramal: "5372", nome: "MARCELO ORANGES", departamento: "DIRETOR" },
  { ramal: "5212", nome: "MARCIO JESUS", departamento: "GRAXARIA" },
  { ramal: "5310", nome: "MARCO ZURITA", departamento: "ADMINISTRATIVO" },
  { ramal: "5246", nome: "MARCOS", departamento: "ETA" },
  { ramal: "5223", nome: "MARCUS PETEAN", departamento: "JURIDICO" },
  { ramal: "5706", nome: "MARIA PIA", departamento: "JURIDICO" },
  { ramal: "5305", nome: "MARLON PIM", departamento: "LOGISTICA" },
  { ramal: "5344", nome: "MATANÇA", departamento: "BALANÇA ABATE" },
  { ramal: "5237", nome: "MATHEUS CLARET BATISTA", departamento: "FISCAL" },
  { ramal: "5106", nome: "MATHEUS FONSECA", departamento: "PROJETOS" },
  { ramal: "5410", nome: "MATHEUS RODRIGUES", departamento: "MANUTENÇÃO" },
  { ramal: "5222", nome: "MATHEUS ZANETTI", departamento: "OPERAÇÕES" },
  { ramal: "5365", nome: "MAURA MERCIA", departamento: "CONTROLE DE QUALIDADE" },
  { ramal: "5313", nome: "MAURICIO HEUSY", departamento: "RH" },
  { ramal: "5449", nome: "MAURICIO ROSSANEIS", departamento: "CONTROLADORIA DE NEGOCIOS" },
  { ramal: "5302", nome: "MAZINHO", departamento: "COMPRA DE GADO" },
  { ramal: "5702", nome: "MURILO CUNHA", departamento: "CONTROLADORIA DE NEGOCIOS" },
  { ramal: "5312", nome: "NAYARA", departamento: "FINANCEIRO" },
  { ramal: "5420", nome: "OFICINA MANUTENÇÃO", departamento: "MANUTENÇÃO" },
  { ramal: "5224", nome: "OLAIR OLIVEIRA", departamento: "COMPRAS" },
  { ramal: "5412", nome: "PABULA", departamento: "COMPRAS" },
  { ramal: "5357", nome: "PAOLA", departamento: "COMERCIAL" },
  { ramal: "5382", nome: "PATRICIA AZEVEDO", departamento: "FISCAL" },
  { ramal: "5327", nome: "PAULO PEREIRA", departamento: "ALMOXARIFADO" },
  { ramal: "5137", nome: "PORCIONADOS", departamento: "DESOSSA" },
  { ramal: "5247", nome: "PORCIONADOS EXP.", departamento: "PORCIONADOS" },
  { ramal: "5301", nome: "PORTARIA", departamento: "PORTARIA" },
  { ramal: "5708", nome: "RAFAEL ALVES", departamento: "PROJETOS" },
  { ramal: "5309", nome: "RAFAEL CARMINATI", departamento: "FINANCEIRO" },
  { ramal: "5243", nome: "RAFAEL GONCALVES", departamento: "FISCAL" },
  { ramal: "5424", nome: "RAFAEL LUCENTE", departamento: "CONTROLADORIA DE NEGOCIOS" },
  { ramal: "5385", nome: "RAMAL DE EMERGÊNCIA", departamento: "PORTARIA" },
  { ramal: "5384", nome: "RAPHAEL RENZZO", departamento: "CONTROLADORIA FINANCEIRA" },
  { ramal: "5350", nome: "RECEPÇÃO", departamento: "RECEPÇÃO" },
  { ramal: "5348", nome: "REFEITORIO", departamento: "REFEITORIO" },
  { ramal: "5326", nome: "RODRIGO SATO", departamento: "EXPORTAÇÃO" },
  { ramal: "5428", nome: "RODRIGO SCHMIDT", departamento: "CONTROLE DE QUALIDADE" },
  { ramal: "5221", nome: "ROGERIO", departamento: "LOGISTICA" },
  { ramal: "5210", nome: "ROGERIO MIGUEL", departamento: "BUCHARIA" },
  { ramal: "5304", nome: "ROGERIO SILVA", departamento: "COMPRA DE GADO" },
  { ramal: "5712", nome: "ROSINALDO", departamento: "Geral" },
  { ramal: "5253", nome: "SALA DE MAQUINAS 2", departamento: "SALA DE MAQUINAS" },
  { ramal: "5333", nome: "SALA DE MAQUINAS 3", departamento: "SALA DE MAQUINAS" },
  { ramal: "5214", nome: "SALA REUNIAO (ALESSANDRA)", departamento: "REUNIAO" },
  { ramal: "5218", nome: "SALA REUNIAO GRANDE", departamento: "REUNIAO" },
  { ramal: "5363", nome: "SALA REUNIAO PEQUENA", departamento: "REUNIAO" },
  { ramal: "5370", nome: "SALA PECUARISTA", departamento: "RECEPÇÃO" },
  { ramal: "5431", nome: "SALA REUNIAO ADM 1", departamento: "ADM" },
  { ramal: "5432", nome: "SALA REUNIAO ADM 2", departamento: "ADM" },
  { ramal: "5433", nome: "SALA REUNIAO ADM 3", departamento: "ADM" },
  { ramal: "5434", nome: "SALA REUNIAO ADM 4", departamento: "ADM" },
  { ramal: "5435", nome: "SALA REUNIAO ADM GRANDE", departamento: "ADM" },
  { ramal: "5234", nome: "SAULO", departamento: "SEGURANÇA DO TRABALHO" },
  { ramal: "5233", nome: "SAULO", departamento: "DHO" },
  { ramal: "5340", nome: "SECRETARIA: VALDICE", departamento: "SIF - SECRETARIA" },
  { ramal: "5355", nome: "SEGURANÇA DO TRABALHO", departamento: "SEGURANÇA DO TRABALHO" },
  { ramal: "5336", nome: "SELSON", departamento: "DESOSSA" },
  { ramal: "5368", nome: "SICA", departamento: "TUNEL" },
  { ramal: "5351", nome: "SILVIA", departamento: "ABATE" },
  { ramal: "5354", nome: "SILVIO ALEXO JUNIOR", departamento: "COMPRAS" },
  { ramal: "5349", nome: "SIMONE", departamento: "MIUDOS" },
  { ramal: "5386", nome: "SUZANNE", departamento: "RASTREABILIDADE" },
  { ramal: "5240", nome: "TAINA SOUZA", departamento: "CONTROLADORIA FINANCEIRA" },
  { ramal: "5315", nome: "TAIS", departamento: "EXPORTAÇÃO" },
  { ramal: "5324", nome: "TALITA MARQUES", departamento: "FINANCEIRO" },
  { ramal: "5402", nome: "TATIANE E RAFAELE", departamento: "CONTROLE DE QUALIDADE" },
  { ramal: "5369", nome: "TAYARA", departamento: "CONTROLADORIA DE NEGOCIOS" },
  { ramal: "5446", nome: "THAISSA", departamento: "Geral" },
  { ramal: "5377", nome: "TI - INDUSTRIA", departamento: "TI - INDUSTRIA" },
  { ramal: "5443", nome: "TI - INDUSTRIA", departamento: "TI - INDUSTRIA" },
  { ramal: "5713", nome: "TRIPARIA", departamento: "TRIPARIA" },
  { ramal: "5215", nome: "TUANE", departamento: "MARKETING" },
  { ramal: "5404", nome: "TULIO BIGHETTI", departamento: "CONFINAMENTO" },
  { ramal: "5381", nome: "VAGO", departamento: "Geral" },
  { ramal: "5373", nome: "VANESSA", departamento: "COMERCIAL" },
  { ramal: "5425", nome: "VANIA FOURNOU", departamento: "P & D" },
  { ramal: "9", nome: "VERA", departamento: "TELEFONISTA" },
  { ramal: "5359", nome: "VICTORIA", departamento: "SUPRIMENTOS" },
  { ramal: "5126", nome: "VINICIUS - PCP", departamento: "PCP" },
  { ramal: "5411", nome: "VINICIUS LUPATO", departamento: "TI" },
  { ramal: "5314", nome: "WADYR", departamento: "CONTROLADORIA DE NEGOCIOS" },
  { ramal: "5232", nome: "WALDEMAR JUNIOR", departamento: "FISCAL" },
  { ramal: "5328", nome: "WANDER", departamento: "ACERTO DE GADO" },
  { ramal: "5437", nome: "WELLINGTON MORAES", departamento: "TI" },
  { ramal: "5703", nome: "WENDEL LUIZ QUERINO", departamento: "PCP" },
  { ramal: "5244", nome: "WILLIAM OLIVEIRA", departamento: "COMERCIAL" },
  { ramal: "5362", nome: "WILSON OLIVEIRA", departamento: "MANUTENÇÃO" },
  { ramal: "5707", nome: "ZECA / JOSÉ VASCONCELOS", departamento: "TI" },
  // Novos ramais da lista fornecida
  { ramal: "5211", nome: "ALEXANDRE OLIVEIRA", departamento: "Geral" },
  { ramal: "5330", nome: "ALMOXARIFADO", departamento: "Geral" },
  { ramal: "1000", nome: "Edson Oliveira", departamento: "Geral" },
  { ramal: "5352", nome: "ELÉTRICA", departamento: "Manutenção" },
  { ramal: "1001", nome: "Felipe Infracom", departamento: "TI" },
  { ramal: "5389", nome: "IARA SILVA", departamento: "Geral" },
  { ramal: "5440", nome: "Joao SUST", departamento: "Sustentabilidade" },
  { ramal: "5394", nome: "LEONARDO PESTANA", departamento: "Geral" },
  { ramal: "5395", nome: "LUIS TEIXEIRA", departamento: "Geral" },
  { ramal: "5376", nome: "MARCELO", departamento: "Geral" },
  { ramal: "5405", nome: "Maria Eugenia", departamento: "Geral" },
  { ramal: "5254", nome: "RAMAL 5254", departamento: "Geral" },
  { ramal: "5408", nome: "RAMAL 5408", departamento: "Geral" },
  { ramal: "5415", nome: "RAMAL 5415", departamento: "Geral" },
  { ramal: "5392", nome: "RODRIGO LOPES", departamento: "Geral" },
];
